cmake_minimum_required(VERSION 3.25)
set(CMAKE_NINJA_CMCLDEPS_RC OFF)
project(GASAIR VERSION 1.0.3.0 LANGUAGES C CXX RC)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(SMTG_USE_STATIC_CRT ON CACHE BOOL "" FORCE)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
set(SMTG_ENABLE_VST3_PLUGIN_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SMTG_ENABLE_VST3_HOSTING_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SMTG_ENABLE_VSTGUI_SUPPORT ON CACHE BOOL "" FORCE)
set(SMTG_RUN_VST_VALIDATOR OFF CACHE BOOL "" FORCE)
set(SMTG_CREATE_MODULE_INFO OFF CACHE BOOL "" FORCE)
set(SMTG_CREATE_PLUGIN_LINK OFF CACHE BOOL "" FORCE)
set(VSTGUI_STANDALONE OFF CACHE BOOL "" FORCE)
set(VSTGUI_STANDALONE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(VSTGUI_TOOLS OFF CACHE BOOL "" FORCE)
set(vst3sdk_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../deps/vst3sdk" CACHE PATH "VST3 SDK")
add_subdirectory("${vst3sdk_SOURCE_DIR}" "${CMAKE_BINARY_DIR}/vst3sdk")
smtg_enable_vst3_sdk()
smtg_add_vst3plugin(GASAIR source/Processor.cpp source/Controller.cpp source/Panel.cpp source/Entry.cpp resource/win32resource.rc)
target_compile_definitions(GASAIR PRIVATE NOMINMAX _CRT_SECURE_NO_WARNINGS)
target_compile_options(GASAIR PRIVATE $<$<COMPILE_LANGUAGE:CXX>:/fp:precise>)
target_link_libraries(GASAIR PRIVATE sdk vstgui_support)
smtg_target_configure_version_file(GASAIR)
smtg_target_add_plugin_resources(GASAIR RESOURCES resource/gasair.uidesc resource/gasair.png)
set_source_files_properties(resource/win32resource.rc PROPERTIES OBJECT_DEPENDS "${CMAKE_CURRENT_BINARY_DIR}/projectversion.h")
